version: 1.1.{build}
image:
  - Visual Studio 2019
  - Ubuntu1604
skip_commits:
  files:
    - '*.md'
    - '*.txt'
    - '.git*'
configuration: Release
init:
- cmd: git config --global core.autocrlf true
before_build:
- dotnet --info
build_script:
- ps: |
    dotnet build --configuration $env:CONFIGURATION
    if ($isWindows) {
      $versionSuffix = ([datetimeoffset]$env:APPVEYOR_REPO_COMMIT_TIMESTAMP).ToUniversalTime().ToString('yyyyMMdd''t''HHmm')
      dotnet pack --configuration $env:CONFIGURATION --version-suffix $versionSuffix
    }
test_script:
- ps: dotnet test
artifacts:
- path: 'dist\*.nupkg'
  name: NuGet
- path: 'dist\*.snupkg'
  name: NuGet (symbols)
