version: 1.1.{build}
image: Visual Studio 2019
skip_commits:
  files:
    - '*.md'
    - '*.txt'
    - '.git*'
configuration: Release
init:
- git config --global core.autocrlf true
before_build:
- dotnet --info
build_script:
- cmd: dotnet build --configuration %CONFIGURATION%
- cmd: IF NOT EXIST dist MKDIR dist
- cmd: dotnet pack --configuration %CONFIGURATION%
test_script:
- cmd: dotnet test
artifacts:
- path: 'dist\*.nupkg'
  name: NuGet
- path: 'dist\*.snupkg'
  name: NuGet (symbols)
